### ISSUE TITLE
Weird graphical issues with Tempest + Hard Crash

### ISSUE THREAD

**Issue by dylanjkl** [lukebemishprojects/Tempest#34]
Weird graphical issues are produced (presumably because of Sodium/Nvidium/Embeddium renderers installed)

Game also randomly hard-crashes.

[crash-2024-01-26_23.22.20-client.txt](https://github.com/lukebemishprojects/Tempest/files/14070104/crash-2024-01-26_23.22.20-client.txt)

![image](https://github.com/lukebemishprojects/Tempest/assets/25552125/1aa6b82b-2eec-47fe-9b9b-167038ea9d7c)

**Comment by lukebemish** [comment]
You probably need a newer version of Embeddium. This was an issue with old versions of it that was fixed in a newer one
