### ISSUE TITLE
Player speed bug during rainy conditions

### ISSUE THREAD

**Issue by dylanjkl** [lukebemishprojects/Tempest#39]
The speed of the player gradually increases astronomically during rainy conditions. Seems to be an issue with friction.

Tested with and without Tempest, may be a mod compatibility issue; unknown.

See example:
https://www.youtube.com/watch?v=xdK8GZrq7Lk

**Comment by lukebemish** [comment]
That's sleet causing black ice on the ground. Black ice basically gets rid of friction. I'm gonna call this intended behavior, I think, though I'll look at adding a config for the intensity of the removal of friction
