### ISSUE TITLE
Shaders Incompatibility

### ISSUE THREAD

**Issue by ColossalRenders** [lukebemishprojects/Tempest#53]
Shaders (tested Comp Re and Photon using Oculus) are unable to detect local weather, as such the sky remains completely clear. Would it be possible to add something client side to trick shaders into thinking that it is snowing/raining? 

Additionally, snow particles (and probably also rain, I haven't yet tested rain) do not render with Photon shaders. Complementary is fine. I had a similar (same?) problem with Weather, Storms and Tornadoes mod and was able to fix it by changing a config to use the vanilla particle system instead. Would that be possible with this mod as well?

**Comment by lukebemish** [comment]
I cannot do anything about this given that weather rendering for Tempest is separate from vanilla weather rendering, anything to "trick" the client into thinking it's raining/snowing would have the unintended consequence of having vanilla rain/snow rendering during storms without shaders, which would look awful. I expose the current weather in my API if other mods doing rendering want to hook into that; I am also more than willing to hook into other people's APIs as needed if they expose proper hooks for stuff. However, there's nothing I can do to fix shaders in general, given that shaders basically just clobber all the stuff I do.

**Comment by lukebemish** [comment]
In terms of using the vanilla particle system: there's a reason I don't do this for the actual weather effects (the rain/snow falling from the sky). They're not particles in vanilla, there's no reason they should be particles in this mod, and in fact doing so would have awful effects on performance. There are places for particles -- think, rain hitting the ground -- but that's the extent of their use here.
