### ISSUE TITLE
An error occurred when entering the created world and when creating a new one.

### ISSUE THREAD

**Issue by FFTSC** [lukebemishprojects/Tempest#7]
When trying to enter the created world / create a new one, an error pops up:
![изображение_2023-12-16_183806108](https://github.com/lukebemishprojects/Tempest/assets/154006192/8bf26527-21e1-4bc8-ae2c-f7d6d584eced)

**Comment by lukebemish** [comment]
Hello,

Please include a log. I will look into this shortly.

**Comment by lukebemish** [comment]
Nevermind, I believe I was able to figure this out without a log; I am releasing a (hopefully) fixed version, let me know if the issue persists with that version.
